In [1]:
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

*** here first oa pack
second is number of list
3rd number of elements ***

In [10]:
import random
random.randint(1,10)

10

In [20]:
np.random.randint(1,10,size=(4,2,5))

array([[[9, 6, 6, 7, 4],
        [2, 2, 9, 5, 9]],

       [[7, 8, 7, 1, 6],
        [7, 7, 7, 1, 6]],

       [[1, 7, 4, 7, 2],
        [1, 7, 2, 2, 6]],

       [[5, 8, 6, 6, 7],
        [5, 3, 2, 5, 4]]])

In [28]:
# Numpy is primarily used for creating arrays wich has faster response time
random.random()
# random values will generate between 0, 1
np.random.rand(2,3, 2)

array([[[0.91109147, 0.77286484],
        [0.64653547, 0.10521676],
        [0.24223256, 0.81978283]],

       [[0.62016935, 0.23736437],
        [0.32770699, 0.80475218],
        [0.22254788, 0.0989859 ]]])

In [40]:
np.full(shape=(3,2),fill_value=7)

array([[7, 7],
       [7, 7],
       [7, 7]])

**Numpy Methods **

In [13]:
arr1=np.array([[10,20,30],[40,50,60]])
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [60]:
arr1.min()
arr1.max()
arr1.mean()
# dir(arr1)
arr1.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [66]:
np.count_nonzero(arr3)

5

In [5]:
import numpy as np
arr3=np.array([[10,0,30],[40,50,60]])

In [7]:
arr5=arr3.sort()
arr3

array([[ 0, 10, 30],
       [40, 50, 60]])

arr5

** Statistical Methods **

In [9]:
data=np.array([10,20,30,40,50])
mean=np.mean(data)
median=np.median(data)
std=np.std(data)
print(f"mean is {mean} median is {median} std is {std}")

mean is 30.0 median is 30.0 std is 14.142135623730951


In [108]:
import pandas as pd
Age=np.array([10,20,30,40,50])
Names=np.array(['Ram','Shyam','Lux','Sumit','Shreya'])
df1=pd.DataFrame(zip(Age,Names), columns=['Age','Names'])
df1
df1['Age']
df2=df1['Age'].values
df2

array([10, 20, 30, 40, 50])

In [120]:
d={}
d['Age']=list(df2)
d['Names']=Names
d

{'Age': [10, 20, 30, 40, 50],
 'Names': array(['Ram', 'Shyam', 'Lux', 'Sumit', 'Shreya'], dtype='<U6')}

In [126]:
# row sum and column sum
arr1
np.sum(arr1)
np.sum(arr1,axis=0) 
# vertical sum when axis=0

array([50, 70, 90])

In [128]:
np.sum(arr1,axis=1)
# horizontal sum when axis=1

array([ 60, 150])

In [131]:
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [135]:
arr5=np.array([[1,2],[2,2]])
arr5.shape

(2, 2)

In [137]:
arr6=np.array([[2,2],[2,1]])
arr6.shape

(2, 2)

In [139]:
np.dot(arr5,arr6)
# np.dot --> Matrix multiplication

array([[6, 4],
       [8, 6]])

In [147]:
# Distance between 2 points
p1=np.array([1,2])
p2=np.array([4,6])
(p2-p1)**2
np.sum((p2-p1)**2)
np.sqrt(np.sum((p2-p1)**2))

5.0

In [149]:
np.linalg.norm(p1-p2)

5.0

In [19]:
# flatten vs Vstack
arr7=arr1.flatten()
arr7
# arr8=arr7.Vstack()
# Combines arryas vertically
arr8=np.vstack((arr1, arr3))
arr8


array([[10, 20, 30],
       [40, 50, 60],
       [ 0, 10, 30],
       [40, 50, 60]])